# Streamlit secrets configuration
# This file is for local development - do not commit to git

[general]
app_name = "Pangeos Feasibility Analyzer"
version = "2.0"
debug_mode = false

[ai_models]
# Free Qwen models from OpenRouter (no API key needed for free tier)
primary_model = "qwen/qwen-2.5-72b-instruct"
backup_models = [
    "qwen/qwen-2-72b-instruct",
    "qwen/qwen-1.5-110b-chat", 
    "qwen/qwen-2.5-7b-instruct"
]

[analysis]
default_timeout = 30
max_retries = 3
cache_duration = 3600

# Optional: Add OpenRouter API key for higher rate limits
# [openrouter]
# api_key = "your_api_key_here"
